version: "3.8"
services:
  web:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  # backend:
  #   build: ./backend
  #   container_name: backend_c
  #   ports:
  #     - "4000:4000"
  #   stdin_open: true
  #   tty: true
